class StuCourseData {
  dynamic id;
  dynamic classPeriods;
  dynamic session;
  dynamic sessionYear;
  dynamic subOfferedId;
  dynamic courseCode;
  dynamic engagedBy;
  dynamic date;
  dynamic classRadius;
  dynamic classOtp;
  dynamic latitude;
  dynamic longitude;
  dynamic classOtpTime;
  dynamic sub_name;
  StudentAttendance? studentAttendance;

  StuCourseData(
      {this.id,
      this.classPeriods,
      this.session,
      this.sessionYear,
      this.subOfferedId,
      this.courseCode,
      this.engagedBy,
      this.date,
      this.classRadius,
      this.classOtp,
      this.latitude,
      this.longitude,
      this.classOtpTime,
      this.sub_name,
      this.studentAttendance});

  StuCourseData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    classPeriods = json['class_periods'];
    session = json['session'];
    sessionYear = json['session_year'];
    subOfferedId = json['sub_offered_id'];
    courseCode = json['course_code'];
    engagedBy = json['engaged_by'];
    date = json['date'];
    classRadius = json['class_radius'];
    classOtp = json['class_otp'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    classOtpTime = json['class_otp_time'];
    sub_name = json['sub_name'];
    studentAttendance = json['student_attendance'] != null
        ? StudentAttendance.fromJson(json['student_attendance'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = id;
    data['class_periods'] = classPeriods;
    data['session'] = session;
    data['session_year'] = sessionYear;
    data['sub_offered_id'] = subOfferedId;
    data['course_code'] = courseCode;
    data['engaged_by'] = engagedBy;
    data['date'] = date;
    data['class_radius'] = classRadius;
    data['class_otp'] = classOtp;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['class_otp_time'] = classOtpTime;
    data['sub_name'] = sub_name;
    if (studentAttendance != null) {
      data['student_attendance'] = studentAttendance!.toJson();
    }
    return data;
  }
}

class StudentAttendance {
  dynamic status;
  dynamic timestamp;

  StudentAttendance({this.status, this.timestamp});

  StudentAttendance.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    timestamp = json['timestamp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['status'] = status;
    data['timestamp'] = timestamp;
    return data;
  }
}

class Autogenerated {
  bool? status;
  List<StuCourseData>? stuCourseData;
  int? presentCount;
  int? absentCount;
  int? totalClass;
  dynamic admnNo;

  Autogenerated(
      {this.status,
      this.stuCourseData,
      this.presentCount,
      this.absentCount,
      this.totalClass,
      this.admnNo});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['Stu_Course_Data'] != null) {
      stuCourseData = <StuCourseData>[];
      json['Stu_Course_Data'].forEach((v) {
        stuCourseData!.add(StuCourseData.fromJson(v));
      });
    }
    presentCount = json['present_count'];
    absentCount = json['absent_count'];
    totalClass = json['total_class'];
    admnNo = json['admn_no'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['status'] = status;
    if (stuCourseData != null) {
      data['Stu_Course_Data'] = stuCourseData!.map((v) => v.toJson()).toList();
    }
    data['present_count'] = presentCount;
    data['absent_count'] = absentCount;
    data['total_class'] = totalClass;
    data['admn_no'] = admnNo;
    return data;
  }
}

class StuCourseDataReport {
  dynamic id;
  dynamic classPeriods;
  dynamic session;
  dynamic sessionYear;
  dynamic subOfferedId;
  dynamic courseCode;
  dynamic engagedBy;
  dynamic date;
  dynamic timestamp;
  dynamic status;
  dynamic attendanceRemark;

  StuCourseDataReport(
      {this.id,
      this.classPeriods,
      this.session,
      this.sessionYear,
      this.subOfferedId,
      this.courseCode,
      this.engagedBy,
      this.date,
      this.timestamp,
      this.status,
      this.attendanceRemark});

  StuCourseDataReport.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    classPeriods = json['class_periods'];
    session = json['session'];
    sessionYear = json['session_year'];
    subOfferedId = json['sub_offered_id'];
    courseCode = json['course_code'];
    engagedBy = json['engaged_by'];
    date = json['date'];
    timestamp = json['timestamp'];
    status = json['status'];
    attendanceRemark = json['attendance_remark'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = id;
    data['class_periods'] = classPeriods;
    data['session'] = session;
    data['session_year'] = sessionYear;
    data['sub_offered_id'] = subOfferedId;
    data['course_code'] = courseCode;
    data['engaged_by'] = engagedBy;
    data['date'] = date;
    data['timestamp'] = timestamp;
    data['status'] = status;
    data['attendance_remark'] = attendanceRemark;
    return data;
  }
}

class StuCourseDatas {
  final int subOfferedId;
  final String subName;
  final String courseCode;
  final String session;
  final String sessionYear;
  final String engagedBy;
  final int totalClasses;
  final int attendedClasses;
  final List<AttendanceDetail> attendanceDetails;

  StuCourseDatas({
    required this.subOfferedId,
    required this.subName,
    required this.courseCode,
    required this.session,
    required this.sessionYear,
    required this.engagedBy,
    required this.totalClasses,
    required this.attendedClasses,
    required this.attendanceDetails,
  });

  // From JSON
  factory StuCourseDatas.fromJson(Map<String, dynamic> json) {
    return StuCourseDatas(
      subOfferedId: json['sub_offered_id'],
      subName: json['sub_name'],
      courseCode: json['course_code'],
      session: json['session'],
      sessionYear: json['session_year'],
      engagedBy: json['engaged_by'],
      totalClasses: json['total_classes'],
      attendedClasses: json['attended_classes'],
      attendanceDetails: (json['attendance_details'] as List)
          .map((item) => AttendanceDetail.fromJson(item))
          .toList(),
    );
  }

  // To JSON
  Map<String, dynamic> toJson() {
    return {
      'sub_offered_id': subOfferedId,
      'sub_name': subName,
      'course_code': courseCode,
      'session': session,
      'session_year': sessionYear,
      'engaged_by': engagedBy,
      'total_classes': totalClasses,
      'attended_classes': attendedClasses,
      'attendance_details':
          attendanceDetails.map((item) => item.toJson()).toList(),
    };
  }
}

class AttendanceDetail {
  final int id;
  final String date;
  final String status;
  final String timestamp;

  AttendanceDetail({
    required this.id,
    required this.date,
    required this.status,
    required this.timestamp,
  });

  // From JSON
  factory AttendanceDetail.fromJson(Map<String, dynamic> json) {
    return AttendanceDetail(
      id: json['id'],
      date: json['date'],
      status: json['status'],
      timestamp: json['timestamp'],
    );
  }

  // To JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'date': date,
      'status': status,
      'timestamp': timestamp,
    };
  }
}
